apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kafka-app.fullname" . }}
{{- if .Values.consumer.serviceAccount.create }}
  labels:
    app: {{ include "kafka-app.name" . }}
{{- end }}

